<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Or you can just email us' => 'Tai voit lähettää myös sähköpostia',
  'Back to front page' => 'Takaisin etusivulle',
  'Email address' => 'Sähköpostiosoite',
  'If you have inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Mikäli sinulla on kysyttävä tapahtumaan koskien, käytä alla olevaa yhteyslomaketta. Kiitos.',
  'Message' => 'Viesti',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Kirjoita kentässä näkyvät kirjaimet tekstikenttään.<br/>Kirjaimen koolla ei ole väliä.',
  'Subject' => 'Aihe',
  'Submit' => 'Lähetä',
  'Thank you for contacting us. We will respond to you as soon as possible.' => 'Kiitos yhteydenotostasi. Vastaamme niin pian kuin voimme.',
  'Verification Code' => 'Vahvistuskoodi',
  'Your name' => 'Nimesi',
);
